name: dev

on:
  push:
    branches: [ dev ]

    # allow manual trigger of workflow 
    workflow_dispatch:

jobs:
  rift-engine:
    name:  Test & Build - Rift Engine 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # adjust this

      - name: Install dependencies
        run: pip install -e .
        working-directory: rift-engine
      - name: Run ruff
        run: ruff check
        working-directory: rift-engine
      - name: Run isort
        run: isort . --check-only --diff
        working-directory: rift-engine
      - name: Run black
        run: black . --check --diff
        working-directory: rift-engine
      - name: Run the program
        run: python -m rift.server.core --port 7797
        working-directory: rift-engine
      - name: commit black formatting
        run: |
          git config --global user.name "kataqatsi"
          git config --global user.email "kataqatsi@gmail.com"
          git add .
          git commit -m "chore: format code with Black"
          git push
        working-directory: rift-engine
  vscode-extension:
    name:  Test & Build - VSCode Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: editors/rift-vscode-svelte
      - name: eslint
        run: npm run lint
        working-directory: editors/rift-vscode-svelte
      - name: prettier
        run: npm run format
        working-directory: editors/rift-vscode-svelte
      - name: compile
        run: npm run compile
        working-directory: editors/rift-vscode-svelte
      - name: commit prettier formatting
        run: |
          git config --global user.name "kataqatsi"
          git config --global user.email "kataqatsi@gmail.com"
          git add .
          git commit -m "chore: format code with Prettier"
          git push
        working-directory: editors/rift-vscode-svelte



